# Generated by Django 2.1.7 on 2019-03-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190301_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Designation',
            new_name='cam',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Qualification',
        ),
    ]
